"""add stored filename to documents

Revision ID: e32f0175812e
Revises: 75c0ea0a7f51
Create Date: 2026-05-12 17:02:43.017554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32f0175812e'
down_revision: Union[str, Sequence[str], None] = '75c0ea0a7f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('stored_filename', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'documents', ['stored_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'stored_filename')
    # ### end Alembic commands ###
